server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/luckysheet?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.luckysheet.luckysheetservice.handler
logging:
  level:
    com.luckysheet.luckysheetservice: debug